# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'expanded.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1218, 907)
        MainWindow.setAutoFillBackground(False)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(0)
        self.splitter.setObjectName("splitter")
        self.taskLayout = QtWidgets.QWidget(self.splitter)
        self.taskLayout.setAutoFillBackground(True)
        self.taskLayout.setObjectName("taskLayout")
        self.seriesPaneLayout = QtWidgets.QVBoxLayout(self.taskLayout)
        self.seriesPaneLayout.setContentsMargins(0, 0, 0, 0)
        self.seriesPaneLayout.setSpacing(0)
        self.seriesPaneLayout.setObjectName("seriesPaneLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.seriesPaneLayout.addItem(spacerItem)
        self.projectList = QtWidgets.QListWidget(self.taskLayout)
        self.projectList.setObjectName("projectList")
        self.seriesPaneLayout.addWidget(self.projectList)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.newButton = QtWidgets.QPushButton(self.taskLayout)
        self.newButton.setObjectName("newButton")
        self.horizontalLayout.addWidget(self.newButton)
        self.deleteButton = QtWidgets.QPushButton(self.taskLayout)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout.addWidget(self.deleteButton)
        self.seriesPaneLayout.addLayout(self.horizontalLayout)
        self.textLayout = QtWidgets.QWidget(self.splitter)
        self.textLayout.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(11)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textLayout.sizePolicy().hasHeightForWidth())
        self.textLayout.setSizePolicy(sizePolicy)
        self.textLayout.setObjectName("textLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.textLayout)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QPlainTextEdit(self.textLayout)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.actionUpdate = QtWidgets.QAction(MainWindow)
        self.actionUpdate.setObjectName("actionUpdate")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionRemove_Credits = QtWidgets.QAction(MainWindow)
        self.actionRemove_Credits.setObjectName("actionRemove_Credits")
        self.action2x = QtWidgets.QAction(MainWindow)
        self.action2x.setObjectName("action2x")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "None"))
        self.newButton.setText(_translate("MainWindow", "New"))
        self.deleteButton.setText(_translate("MainWindow", "Delete"))
        self.actionUpdate.setText(_translate("MainWindow", "Update All"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSettings.setText(_translate("MainWindow", "Settings..."))
        self.actionRemove_Credits.setText(_translate("MainWindow", "Remove Credits"))
        self.action2x.setText(_translate("MainWindow", "2x"))
